// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPyz7OnC9-ykuDX_zIqpFZIDkdS8wPNFY',
    appId: '1:383004763737:web:71dd34fc4b6add12afb348',
    messagingSenderId: '383004763737',
    projectId: 'videoapp-d968d',
    authDomain: 'videoapp-d968d.firebaseapp.com',
    storageBucket: 'videoapp-d968d.appspot.com',
    measurementId: 'G-DEXM4YY1BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnpedOiXlRu21_U7xt744thV2tIdV_HkY',
    appId: '1:383004763737:android:5ab6f97d9cdca342afb348',
    messagingSenderId: '383004763737',
    projectId: 'videoapp-d968d',
    storageBucket: 'videoapp-d968d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt1pxj_-wc58X-IPbsZkzbGPBcvi12r8c',
    appId: '1:383004763737:ios:cc406bc0171f6722afb348',
    messagingSenderId: '383004763737',
    projectId: 'videoapp-d968d',
    storageBucket: 'videoapp-d968d.appspot.com',
    iosBundleId: 'com.example.videoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt1pxj_-wc58X-IPbsZkzbGPBcvi12r8c',
    appId: '1:383004763737:ios:cc406bc0171f6722afb348',
    messagingSenderId: '383004763737',
    projectId: 'videoapp-d968d',
    storageBucket: 'videoapp-d968d.appspot.com',
    iosBundleId: 'com.example.videoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPyz7OnC9-ykuDX_zIqpFZIDkdS8wPNFY',
    appId: '1:383004763737:web:330538cd7e554facafb348',
    messagingSenderId: '383004763737',
    projectId: 'videoapp-d968d',
    authDomain: 'videoapp-d968d.firebaseapp.com',
    storageBucket: 'videoapp-d968d.appspot.com',
    measurementId: 'G-9WQL4KK01Y',
  );
}
